In [5]:
import numpy as np
import timeit

    1. Выполнить обработку элементов матрицы А, имеющей N строк и М столбцов. Найти наибольшее значение среди средних значений для каждой строки матрицы. Сделать с помощью numpy (mean и max) и без него. Замерить время выполнения программы.

In [ ]:
%%timeit
a = np.random.rand(4, 5)

mean_strs = []
for i in range(4):
    x = 0
    for j in range(5):
        x += a[i][j]
    mean_strs.append(x/5)
max(mean_strs)

7.58 μs ± 50.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [16]:
%%timeit
np.max(np.mean(a, axis=1))

10.1 μs ± 76.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


    2. Выполнить обработку элементов матрицы А, имеющей N строк и М столбцов. Найти наименьший элемент строки матрицы А, для которого сумма абсолютных значений элементов максимальна (np.argmax и np.min). Замерить время выполнения программы.

In [24]:
%%timeit
a = np.random.rand(4, 5)
abs_sums = np.sum(np.abs(a), axis = 1)

min_i = 0
min_sum = abs_sums[0]
for i, str in enumerate(abs_sums):
    if str < min_sum:
        min_sum = str
        min_i = i

min_i

6.13 μs ± 179 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


    3. Выполнить обработку элементов матрицы А, имеющей N строк и М столбцов. Найти наименьшее значение среди средних значений для каждого столбца матрицы. Замерить время выполнения программы.

In [26]:
%%timeit
a = np.random.rand(4, 5)
np.min(np.mean(a, axis=0))

11.8 μs ± 88.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


    4. Выполнить обработку элементов матрицы А, имеющей N строк и М столбцов. Определить средние значения по всем строкам, столбцам матрицы и по всей матрицы. Замерить время выполнения программы.

In [28]:
%%timeit
a = np.random.rand(4, 5)
print(np.mean(a, axis=1), np.mean(a, axis=0), np.min(a))

[0.40857477 0.32589124 0.5313871  0.56232637] [0.63361638 0.29106166 0.46116198 0.48258479 0.41679954] 0.11248867678008756
[0.61517606 0.71146407 0.43409986 0.62734467] [0.58903138 0.5474354  0.74472095 0.71197961 0.39193848] 0.10112336380198761
[0.51465211 0.29880257 0.44579994 0.62677475] [0.44104352 0.51532532 0.49892189 0.47376273 0.42848326] 0.034329621409295186
[0.59214807 0.31155218 0.43654594 0.50290747] [0.24257591 0.49482764 0.53843866 0.48091909 0.54718077] 0.03077133422288081
[0.53441295 0.63733265 0.22856471 0.68663196] [0.40276958 0.66544695 0.59671936 0.28563511 0.65810685] 0.06371243870952825
[0.60489002 0.36644586 0.6721249  0.69289198] [0.72951891 0.61280988 0.42886089 0.42672035 0.72253092] 0.1080942018319514
[0.4248093  0.33295014 0.53855922 0.74051536] [0.39217316 0.4417361  0.3559537  0.69084835 0.66533121] 0.021360351911830167
[0.39215053 0.36309253 0.37735916 0.40232169] [0.54059218 0.30814061 0.45159936 0.43477274 0.18354999] 0.008902871120146538
[0.23354794 0.

    5. Выполнить обработку элементов матрицы A, имеющей N строк и M столбцов. Каждый элемент подматрицы, умножить на заданное число. Замерить время выполнения программы.


In [29]:
%%timeit
a = np.random.rand(4, 5)
a*3

2.18 μs ± 4.97 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
