In [1]:
import numpy as np

    1. Создание одномерного массива с использованием np.array().
        ◦ Создайте одномерный массив из чисел от 1 до 10 с помощью np.array().
    2. Создание массива из нулей с помощью np.zeros().
        ◦ Создайте массив из 7 элементов, заполненных нулями.
    3. Создание массива из единиц с помощью np.ones().
        ◦ Создайте массив из 5 единиц.
    4. Создание массива с последовательностью чисел с использованием np.arange().
        ◦ Создайте массив от 10 до 50 с шагом 5.
    5. Создание массива с линейно распределенными числами с помощью np.linspace().
        ◦ Создайте массив из 6 чисел, равномерно распределенных от 0 до 100.

In [7]:
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.arange(10, 51, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [11]:
np.linspace(0, 100, 6)

array([  0.,  20.,  40.,  60.,  80., 100.])

    6. Индексация массива.
        ◦ Создайте массив и выведите второй элемент, последний элемент и элементы с индексами от 3 до 6.
    7. Итерация по массиву с использованием цикла for.
        ◦ Создайте одномерный массив и выведите его элементы с помощью цикла.
    8. Сложение двух массивов.
        ◦ Создайте два массива одинаковой длины и сложите их поэлементно.
    9. Умножение массива на число.
        ◦ Создайте массив и умножьте все его элементы на 2.
    10. Возведение элементов массива в квадрат.
        ◦ Создайте массив и возведите все его элементы в квадрат.

In [13]:
a = np.arange(1, 11)
print(a[1], a[-1])
print(a[3:7])

2 10
[4 5 6 7]


In [14]:
for el in a:
    print(el, end=" ")

1 2 3 4 5 6 7 8 9 10 

In [15]:
b = np.arange(11, 21)
for i in range(len(a)):
    b[i] += a[i]
b

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [16]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [17]:
a*a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

    11. Поиск минимального и максимального значений в массиве.
        ◦ Создайте массив и найдите его минимум и максимум с использованием функций np.min() и np.max().
    12. Вычисление среднего значения и стандартного отклонения.
        ◦ Создайте массив и вычислите его среднее значение и стандартное отклонение.
    13. Использование логарифма, экспоненты и синуса для элементов массива.
        ◦ Примените к элементам массива функции np.log(), np.exp() и np.sin().
    14. Генерация случайных чисел с использованием np.random.rand().
        ◦ Создайте массив из 10 случайных чисел, распределенных от 0 до 1.
    15. Генерация случайных целых чисел с использованием np.random.randint().
        ◦ Создайте массив из 6 случайных целых чисел от 1 до 100.

In [18]:
np.min(a), np.max(a)

(np.int64(1), np.int64(10))

In [19]:
np.mean(a), np.std(a)

(np.float64(5.5), np.float64(2.8722813232690143))

In [20]:
print(np.log(a))
print(np.exp(a))
print(np.sin(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]


In [21]:
np.random.rand(10)

array([0.48966103, 0.35446374, 0.07857954, 0.56271728, 0.77943733,
       0.27102118, 0.83903821, 0.40283786, 0.95559016, 0.85624972])

In [22]:
np.random.randint(1, 100, size=6)

array([ 1,  8,  8, 90, 63, 25])

    16. Преобразование одномерного массива в двумерный.
        ◦ Преобразуйте одномерный массив в двумерный массив с 2 строками и 5 столбцами.
    17. Изменение формы массива с использованием reshape().
        ◦ Измените форму одномерного массива с 9 элементами на двумерный массив 3x3.
    18. Фильтрация массива с использованием условия.
        ◦ Создайте массив и выберите только те элементы, которые больше 5.
    19. Использование np.vectorize() для применения функции ко всем элементам массива.
        ◦ Создайте массив и примените функцию возведения в куб ко всем его элементам с помощью np.vectorize().
    20. Сохранение и загрузка массива в/из файла.
        ◦ Сохраните одномерный массив в файл .npy и загрузите его обратно в программу.

In [26]:
a = np.arange(10)
b = np.zeros((2, 5))
for i in range(2):
    for j in range(5):
        b[i][j] = a[i*5 + j]
b

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [27]:
a = np.arange(9)
a.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
a[a>5]

array([6, 7, 8, 9])

In [37]:
a = np.arange(10)
def func(a):
    return a**3
vfunc = np.vectorize(func)
vfunc(a)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [28]:
a = np.arange(10)
np.save('data', a)

In [29]:
data = np.load('data.npy')
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])