In [1]:
import numpy as np

Задания на создание двумерных массивов  
    1. Создание массива с помощью np.array:  
        ◦ Создайте двумерный массив размером 4x4, содержащий числа от 1 до 16.  
    2. Создание массива с помощью np.zeros:  
        ◦ Создайте массив размером 5x5, заполненный нулями.  
    3. Создание массива с помощью np.ones:  
        ◦ Создайте массив размером 3x6, заполненный единицами.  
    4. Создание единичной матрицы с помощью np.eye:  
        ◦ Создайте единичную матрицу размером 4x4.  
    5. Создание массива с помощью np.random.rand:  
        ◦ Создайте массив размером 2x3, заполненный случайными числами от 0 до 1.  

In [2]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.random.rand(2, 3)

array([[0.15938758, 0.82634451, 0.15085497],
       [0.82872846, 0.47231542, 0.99474788]])

Задания на атрибуты двумерных массивов   
    6. Определение размерности массива:  
        ◦ Создайте массив размером 3x4 и выведите его размерность (ndim).  
    7. Определение формы массива:  
        ◦ Создайте массив размером 2x5 и выведите его форму (shape).  
    8. Определение общего количества элементов:  
        ◦ Создайте массив размером 4x3 и выведите общее количество элементов (size).  
    9. Определение типа данных элементов массива:  
        ◦ Создайте массив размером 3x3 и выведите тип данных его элементов (dtype).  

In [10]:
a = np.ones((3, 4))
a.ndim

2

In [11]:
a = np.ones((2, 5))
a.shape

(2, 5)

In [12]:
a = np.ones((4, 3))
a.size

12

In [13]:
a = np.ones((3, 3))
a.dtype

dtype('float64')

Задания на индексацию и срезы   
    10. Индексация элемента:  
        ◦ Создайте массив размером 3x3 и выведите элемент, находящийся во второй строке и третьем столбце.  
    11. Срез строки:  
        ◦ Создайте массив размером 4x4 и выведите вторую строку целиком.  
    12. Срез столбца:  
        ◦ Создайте массив размером 5x5 и выведите третий столбец целиком.  
    13. Срез подмассива:  
        ◦ Создайте массив размером 6x6 и выведите подмассив, состоящий из первых трех строк и первых трех столбцов.  


In [22]:
a = np.eye(3)
a[1, 2]

np.float64(0.0)

In [16]:
a = np.eye(4)
a[1]

array([0., 1., 0., 0.])

In [21]:
a = np.eye(5)
a[:, 2]

array([0., 0., 1., 0., 0.])

In [20]:
a = np.eye(6)
a[:3, :3]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Задания на изменение формы массива  
    14. Преобразование массива в одномерный:  
        ◦ Создайте двумерный массив размером 3x3 и преобразуйте его в одномерный массив с помощью метода flatten.  
    15. Изменение формы массива:  
        ◦ Создайте массив размером 2x6 и преобразуйте его в массив размером 3x4 с помощью метода reshape.  

In [23]:
a = np.eye(3)
a.flatten()

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [25]:
a = np.random.rand(2, 6)
a

array([[0.38809599, 0.04104169, 0.47145458, 0.48116805, 0.66916168,
        0.509454  ],
       [0.75512873, 0.30332379, 0.45373339, 0.17226588, 0.55360443,
        0.87845362]])

In [26]:
a.reshape((3, 4))

array([[0.38809599, 0.04104169, 0.47145458, 0.48116805],
       [0.66916168, 0.509454  , 0.75512873, 0.30332379],
       [0.45373339, 0.17226588, 0.55360443, 0.87845362]])

Задания на математические операции  
    16. Сложение двух массивов:  
        ◦ Создайте два массива размером 2x2 и сложите их поэлементно.  
    17. Умножение массива на число:  
        ◦ Создайте массив размером 3x3 и умножьте каждый его элемент на 5.  
    18. Поэлементное умножение массивов:  
        ◦ Создайте два массива размером 2x2 и перемножьте их поэлементно.  

In [27]:
a = np.ones((2, 2))
b = np.full((2, 2), 5)
a+b

array([[6., 6.],
       [6., 6.]])

In [28]:
a = np.ones((3, 3))
a*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [31]:
a = np.full((2, 2), 2)
b = np.full((2, 2), 5)
a*b

array([[10, 10],
       [10, 10]])

Задания на статистические операции  
    19. Среднее значение по всем элементам:  
        ◦ Создайте массив размером 4x4 и вычислите среднее значение всех его элементов.  
    20. Среднее значение по строкам:  
        ◦ Создайте массив размером 3x3 и вычислите среднее значение по каждой строке.  
    21. Среднее значение по столбцам:  
        ◦ Создайте массив размером 5x5 и вычислите среднее значение по каждому столбцу.  
    22. Минимум и максимум:  
        ◦ Создайте массив размером 4x4 и найдите минимальное и максимальное значение в массиве.  
    23. Сумма всех элементов:  
        ◦ Создайте массив размером 3x3 и вычислите сумму всех его элементов.  


In [32]:
a = np.random.rand(4, 4)
a.mean()

np.float64(0.5965967973955507)

In [33]:
a = np.random.rand(3, 3)
a.mean(axis=1)

array([0.57163851, 0.32655755, 0.38808747])

In [34]:
a = np.random.rand(5, 5)
a.mean(axis=0)

array([0.26218029, 0.58670312, 0.33202285, 0.45656516, 0.57378022])

In [35]:
a = np.random.rand(4, 4)
a.min(), a.max()

(np.float64(0.004413785383538205), np.float64(0.8739372526202022))

In [36]:
a = np.random.rand(3, 3)
a.sum()

np.float64(4.9372712862427965)

Задания на транспонирование массива  
    24. Транспонирование массива:  
        ◦ Создайте массив размером 2x3 и транспонируйте его.  


In [37]:
a = np.random.rand(2, 3)
a

array([[0.93250353, 0.22704965, 0.26424601],
       [0.75852298, 0.32665029, 0.73297209]])

In [38]:
a.T

array([[0.93250353, 0.75852298],
       [0.22704965, 0.32665029],
       [0.26424601, 0.73297209]])

Задания на сохранение и загрузку массивов  
    25. Сохранение массива в файл:  
        ◦ Создайте массив размером 3x3 и сохраните его в файл в формате .npy.  
    26. Загрузка массива из файла:  
        ◦ Загрузите массив из файла .npy и выведите его на экран.  
    27. Сохранение массива в текстовый файл:  
        ◦ Создайте массив размером 2x2 и сохраните его в текстовый файл.  
    28. Загрузка массива из текстового файла:  
        ◦ Загрузите массив из текстового файла и выведите его на экран.  

In [39]:
a = np.random.rand(3, 3)
np.save('data', a)

In [40]:
np.load('data.npy')

array([[0.21279829, 0.31531311, 0.95374277],
       [0.25087129, 0.92200072, 0.98902859],
       [0.77792129, 0.28182827, 0.4538773 ]])

In [ ]:
a = np.random.rand(2, 2)

In [54]:
np.savetxt('data.txt', a)

In [56]:
np.loadtxt('data.txt')

array([[0.48280947, 0.52974213],
       [0.41102613, 0.37151207]])

Задания на итерацию по массиву  
    29. Итерация по строкам:  
        ◦ Создайте массив размером 3x3 и выведите каждую строку массива.  
    30. Итерация по элементам:  
        ◦ Создайте массив размером 2x4 и выведите каждый элемент массива.  

In [60]:
a = np.random.rand(3, 3)
for line in a:
    print(line)

[0.87401697 0.52659741 0.01039808]
[0.10086577 0.07215468 0.39161042]
[0.2483198  0.29314616 0.98422435]


In [61]:
for line in a:
    for el in line:
        print(el)

0.8740169739662711
0.526597407519871
0.010398083580888673
0.10086576752248733
0.07215468187519114
0.39161041614681946
0.2483198019226971
0.2931461639802585
0.984224345075926
